### ISSUE TITLE
Cannot copy files bigger than one cluster

### ISSUE THREAD

**Issue by schilive** [qihaiyan/fat12#1]
When I tried copying a file bigger than one cluster into a floppy image with the following conditions, it did not work. The FAT was not updated. Looking at the image using a hex editor, I saw a weird part was updated as if it were the FAT.

1. The number of bytes per sector is 512.
2. The number of sectors per cluster is 4.
3. The number of FATs is 2.
4. The number of reserved sectors is 1.

Reading the source code, I found two functions calculating the offset of an entry in the FAT: `get_fat_entry()` and `set_fat_entry()`, on `dos.c`. For some reason, the number of sectors per cluster was used. I found this odd, since the FAT entry offset is (usually) calculated by finding the FAT offset and then adding `entry_number * 1.5`.

By removing the count of sectors per cluster, the problem was fixed. If you'd like, I can just make a pull request with this change.

**Comment by qihaiyan** [comment]
PR please @Schilive

**Comment by schilive** [comment]
I have made the pull request, but I thought that by the tile having "Fix #1", it would show here, but no... I am sorry.
